// @ts-check
'use strict';

const { deepMergeConfig } = require('@-xun/symbiote/assets');

const {
  assertEnvironment,
  moduleExport
} = require('@-xun/symbiote/assets/babel.config.cjs');

const { createDebugLogger } = require('rejoinder');

const debug = createDebugLogger({ namespace: 'symbiote:config:babel' });

module.exports = deepMergeConfig(
  moduleExport({
    derivedAliases: getBabelAliases(),
    ...assertEnvironment({ projectRoot: __dirname })
  }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
    // You may wish to enable explicit exports references for improved testing
    // DX, but be aware that it is currently a wee buggy as of 5/2025 (fix it!)
    //
    // env: {
    //   test: {
    //     plugins: ['babel-plugin-explicit-exports-references']
    //   }
    // }
  }
);

// TODO: delete this
if (process.env.EXTERNAL_DELETE_THIS) {
  // @ts-expect-error: delete all of this
  module.exports.env['production-cjs'].plugins[0][1].replaceExtensions[
    '^../test/util.js$'
  ] = './util.js';
}

debug('exported config: %O', module.exports);

function getBabelAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^universe:(.+)$': './src/$1',
    '^universe$': './src/index.js',
    '^testverse:(.+)$': './test/$1',
    '^typeverse:(.+)$': './types/$1',
    '^rootverse:(.+)$': './$1'
  };
}
