// @ts-check
'use strict';

const { deepMergeConfig } = require('@-xun/symbiote/assets');

const {
  assertEnvironment,
  moduleExport
} = require('@-xun/symbiote/assets/babel.config.cjs');

const { createDebugLogger } = require('rejoinder');

const debug = createDebugLogger({ namespace: 'symbiote:config:babel' });

const config = deepMergeConfig(
  moduleExport({
    derivedAliases: getBabelAliases(),
    ...assertEnvironment({ projectRoot: __dirname })
  }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
    //
    // You may wish to enable explicit exports references for improved testing
    // DX, but be aware that it is currently a wee buggy as of 5/2025 (fix it!)
    //
    // env: {
    //   test: {
    //     plugins: ['babel-plugin-explicit-exports-references']
    //   }
    // }
  }
);

module.exports = config;
debug('exported config: %O', module.exports);

function getBabelAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+get\\x2dnextjs\\x2dreact\\x2dpeer\\x2ddependencies:(.+)$':
      './packages/get-nextjs-react-peer-dependencies/src/$1',
    '^multiverse\\+is\\x2dnext\\x2dcompat:(.+)$': './packages/is-next-compat/src/$1',
    '^multiverse\\+shared:(.+)$': './packages/shared/src/$1',
    '^multiverse\\+get\\x2dnextjs\\x2dreact\\x2dpeer\\x2ddependencies$':
      './packages/get-nextjs-react-peer-dependencies/src/index.js',
    '^multiverse\\+is\\x2dnext\\x2dcompat$': './packages/is-next-compat/src/index.js',
    '^multiverse\\+shared$': './packages/shared/src/index.js',
    '^universe\\+get\\x2dnextjs\\x2dreact\\x2dpeer\\x2ddependencies:(.+)$':
      './packages/get-nextjs-react-peer-dependencies/src/$1',
    '^universe\\+is\\x2dnext\\x2dcompat:(.+)$': './packages/is-next-compat/src/$1',
    '^universe\\+shared:(.+)$': './packages/shared/src/$1',
    '^universe\\+get\\x2dnextjs\\x2dreact\\x2dpeer\\x2ddependencies$':
      './packages/get-nextjs-react-peer-dependencies/src/index.js',
    '^universe\\+is\\x2dnext\\x2dcompat$': './packages/is-next-compat/src/index.js',
    '^universe\\+shared$': './packages/shared/src/index.js',
    '^universe:(.+)$': './src/$1',
    '^universe$': './src/index.js',
    '^testverse\\+get\\x2dnextjs\\x2dreact\\x2dpeer\\x2ddependencies:(.+)$':
      './packages/get-nextjs-react-peer-dependencies/test/$1',
    '^testverse\\+is\\x2dnext\\x2dcompat:(.+)$': './packages/is-next-compat/test/$1',
    '^testverse\\+shared:(.+)$': './packages/shared/test/$1',
    '^testverse:(.+)$': './test/$1',
    '^typeverse:(.+)$': './types/$1',
    '^rootverse\\+get\\x2dnextjs\\x2dreact\\x2dpeer\\x2ddependencies:(.+)$':
      './packages/get-nextjs-react-peer-dependencies/$1',
    '^rootverse\\+is\\x2dnext\\x2dcompat:(.+)$': './packages/is-next-compat/$1',
    '^rootverse\\+shared:(.+)$': './packages/shared/$1',
    '^rootverse:(.+)$': './$1'
  };
}
